# Add configuration values.

development:
  TWILIO_ACCOUNT_SID: <%= ENV['TWILIO_ACCOUNT_SID']%>
  TWILIO_CONFIGURATION_SID: <%= ENV['TWILIO_CONFIGURATION_SID']%>
  TWILIO_API_KEY: <%= ENV['TWILIO_API_KEY'] %>
  TWILIO_API_SECRET: <%= ENV['TWILIO_API_SECRET'] %>
  TWILIO_PHONE_NUMBER: <%= ENV['TWILIO_PHONE_NUMBER'] %>
  TWILIO_AUTH_TOKEN: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  SMTP_USER_NAME: <%= ENV['SMTP_USER_NAME']%>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD']%>

test:
  TWILIO_ACCOUNT_SID: <%= ENV['TWILIO_ACCOUNT_SID']%>
  TWILIO_CONFIGURATION_SID: <%= ENV['TWILIO_CONFIGURATION_SID']%>
  TWILIO_API_KEY: <%= ENV['TWILIO_API_KEY'] %>
  TWILIO_API_SECRET: <%= ENV['TWILIO_API_SECRET'] %>
  TWILIO_PHONE_NUMBER: <%= ENV['TWILIO_PHONE_NUMBER'] %>
  TWILIO_AUTH_TOKEN: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  SMTP_USER_NAME: <%= ENV['SMTP_USER_NAME']%>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD']%>